# Site settings
title: "Hedge-o-Mat - on financial risk management"
email: ""  #"hedge-o-mat AT apax .net"
description: "understanding and managing financial risks."
####baseurl: "http://codiepp.github.io/Hedge-o-Mat"
url: "http://codiepp.github.io/Hedge-o-Mat"
twitter_username: CodiePlusPlus
github_username:  CodiePP

# Build settings
markdown: kramdown
permalink: pretty

source: .
destination: ../../Hedge-o-Mat.pages/

# build index
lsi: false

# permalink as /Hedge-o-Mat/:categories/:title.html
permalink: none

# Serving by 'jekyll serve -w'
detach:  false
port:    4000
host:    127.0.0.1
baseurl: "/Hedge-o-Mat" # does not include hostname

