# Site settings
title: "Hedge-o-Mat - your personal financial risk manager"
email: "hedge-o-mat AT apax .net"
description: "Hedge-o-Mat helps you manage financial risks."
baseurl: ""
url: "http://codiepp.github.io/Hedge-o-Mat"
twitter_username: CodiePlusPlus
github_username:  CodiePP

# Build settings
markdown: kramdown
permalink: pretty

source: .
destination: ../../Hedge-o-Mat.pages/

# build index
lsi: true

# permalink as /:categories/:title.html
permalink: none


